# Generated by Django 4.1.5 on 2023-01-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_casetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
