# Generated by Django 4.1.5 on 2023-02-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_remove_feedback_user_remove_req_agency_and_more'),
        ('Guest', '0007_remove_user_place_delete_agency_delete_user'),
        ('Admin', '0004_district_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casetype',
        ),
        migrations.RemoveField(
            model_name='place',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
