# Generated by Django 4.1.5 on 2023-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_mail', models.CharField(max_length=100)),
                ('admin_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
