# Generated by Django 4.1.5 on 2023-02-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
