# Generated by Django 4.1.5 on 2023-01-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
