# Generated by Django 4.1.5 on 2023-02-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_delete_req'),
        ('Guest', '0004_agency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
