# Generated by Django 4.1.5 on 2023-02-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
