# Generated by Django 4.1.5 on 2023-03-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_remove_complaint_user_remove_feedback_user_and_more'),
        ('Guest', '0011_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
