# Generated by Django 4.1.5 on 2023-04-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_remove_complaint_user_remove_feedback_user_and_more'),
        ('Guest', '0013_user_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
