# Generated by Django 4.1.5 on 2023-01-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Req',
        ),
    ]
