# Generated by Django 4.1.5 on 2023-02-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Req',
        ),
    ]
