# Generated by Django 4.1.5 on 2023-03-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='req',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='req',
            name='casetype',
        ),
        migrations.RemoveField(
            model_name='req',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Req',
        ),
    ]
