# Generated by Django 4.1.5 on 2023-04-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_req'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Req',
        ),
    ]
