# Generated by Django 4.1.5 on 2023-04-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Req',
        ),
    ]
