# Generated by Django 4.1.5 on 2023-04-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_req'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Req',
        ),
    ]
